version: '3'
services:
  server:
    build:
      context: ..
      dockerfile: docker/server.dockerfile
    volumes:
      - ${PWD}/../volumes/log:/var/log
      - ${PWD}/../volumes/tmp:/var/tmp
    environment:
      - MYSQL_DB_HOST=${DB_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "8080:8080"
    container_name: "wechat-bot-server"
    restart: always

  db:
    image: mysql:5.7
    volumes:
      - ${PWD}/../volumes/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    container_name: "wechat-bot-mysql"
    restart: always

  redis:
    image: redis:4.0
    volumes:
      - ${PWD}/../volumes/redis_data:/data
    ports:
      - "127.0.0.1:6379:6379"
    container_name: "wechat-bot-redis"
    restart: always
